name: Filza26Maker Build

on:
  workflow_dispatch:
    inputs:
      filza_url:
        description: "Direct download URL for Filza IPA or DEB"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip wget curl tar p7zip-full

      - name: Download Filza file
        run: |
          echo "Downloading Filza from ${{ github.event.inputs.filza_url }}"
          wget -O FilzaInput $(echo "${{ github.event.inputs.filza_url }}")
          ls -lh FilzaInput

      - name: Make script executable
        run: chmod +x ./Filza26Maker.sh

      - name: Run Filza26Maker
        run: |
          echo "Running Filza26Maker..."
          ./Filza26Maker.sh FilzaInput || ./Filza26Maker.sh
          echo "Build script finished."

      - name: Detect output and zip it
        run: |
          mkdir -p final_output
          echo "Collecting possible output files..."
          # Gather any IPA, ZIP, or folders that look like output
          find . -maxdepth 2 -type f \( -name "*.ipa" -o -name "*.zip" \) -exec cp {} final_output/ \; || true
          find . -maxdepth 2 -type d \( -name "output" -o -name "build" -o -name "dist" \) -exec cp -r {} final_output/ \; || true

          # If still empty, zip everything
          if [ -z "$(ls -A final_output)" ]; then
            echo "No specific outputs found. Zipping repo contents instead..."
            zip -r Filza26_AllFiles.zip .
            mv Filza26_AllFiles.zip final_output/
          fi

          # Zip final output folder
          zip -r Filza26_Output.zip final_output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Filza26_output
          path: final_output/Filza26_Output.zip
